version: 2.1

executors:
  apisuite-executor:
    environment:
      SHOULD_TEST: "false"
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/apisuite

jobs:
  test:
      executor: apisuite-executor
      steps:
        - checkout
        - run:
            name: Run tests
            command: |
              cd util
              chmod +x common.sh
              chmod +x run_tests.sh
              chmod +x install_dependencies.sh
              [[ $SHOULD_TEST == "false" ]] && echo "Bypass tests" || (./install_dependencies.sh && ./run_tests.sh)

  build:
      executor: apisuite-executor
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build packages with docker-compose and push to registry
            command: |
              sudo apt-get install ruby-full jq
              cd util
              chmod +x build_push_docker.sh
              ./build_push_docker.sh
        - persist_to_workspace:
              root: ./util
              paths:
                - .env

  deploy:
      executor: apisuite-executor
      steps:
        - checkout
        - attach_workspace:
            at: ./util
        - run:
            name: Fix ssh could not resolve hostname
            command: |
              ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
        - add_ssh_keys:
            fingerprints:
              - "92:92:37:9c:7c:b4:e2:93:0a:f7:ac:f7:c6:74:b8:61"
        - run:
            name: Deploy Over SSH
            command: |
              chmod +x ./util/clean_compose.sh
              (cd ./util && ./clean_compose.sh)
              scp -o StrictHostKeyChecking=no ./util/.env ./util/docker-compose.yml $DROPLET_USER@$DROPLET_IP:/apps/APISuite/
              ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "cd /apps/APISuite/ && docker-compose pull && docker-compose up -d && docker image prune --force"

workflows:
  version: 2
  build:
    jobs:
        - test
        - build:
            filters:
                branches:
                  only:
                    - develop
            requires:
                - test
        - deploy:
            filters:
                branches:
                  only:
                    - develop
            requires:
                - build
