version: 2.1

executors:
  apisuite-executor:
    environment:
      SHOULD_TEST: "false"
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/apisuite

jobs:
  test:
      executor: apisuite-executor
      steps:
        - checkout
        - run:
            name: Run tests
            command: |
              cd util
              chmod +x common.sh
              chmod +x run_tests.sh
              chmod +x install_dependencies.sh
              [[ $SHOULD_TEST == "false" ]] && echo "Bypass tests" || (./install_dependencies.sh && ./run_tests.sh)

  build:
      executor: apisuite-executor
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build packages with docker-compose and push to registry
            command: |
              sudo apt-get install ruby-full jq
              cd util
              chmod +x build_push_docker.sh
              ./build_push_docker.sh
        - persist_to_workspace:
              root: ./util
              paths:
                - .env

  deploy-dev:
      executor: apisuite-executor
      steps:
        - checkout
        - attach_workspace:
            at: ./util
        - run:
            name: Fix ssh could not resolve hostname
            command: |
              ssh-keyscan $DROPLET_IP_DEV >> ~/.ssh/known_hosts
        - add_ssh_keys:
            fingerprints:
              - "92:92:37:9c:7c:b4:e2:93:0a:f7:ac:f7:c6:74:b8:61"
        - run:
            name: Deploy Over SSH
            command: |
              chmod +x ./util/clean_compose.sh
              (cd ./util && ./clean_compose.sh)
              chmod +x ./util/merge_env.sh
              scp -o StrictHostKeyChecking=no ./util/.env ./util/environment ./util/docker-compose.yml ./util/merge_env.sh $DROPLET_USER@$DROPLET_IP_DEV:/apps/APISuite/
              ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP_DEV "cd /apps/APISuite/ && ./merge_env.sh && docker-compose pull && docker-compose up -d && docker image prune --force"

  deploy-stg:
      executor: apisuite-executor
      steps:
        - checkout
        - attach_workspace:
            at: ./util
        - run:
            name: Fix ssh could not resolve hostname
            command: |
              ssh-keyscan $DROPLET_IP_STG >> ~/.ssh/known_hosts
        - add_ssh_keys:
            fingerprints:
              - "5d:31:e4:99:b3:31:14:d9:2e:50:b7:1f:8f:b8:f3:ab"
        - run:
            name: Deploy Over SSH
            command: |
              chmod +x ./util/clean_compose.sh
              (cd ./util && ./clean_compose.sh)
              chmod +x ./util/merge_env.sh
              scp -o StrictHostKeyChecking=no ./util/.env ./util/environment ./util/docker-compose.yml ./util/merge_env.sh $DROPLET_USER@$DROPLET_IP_STG:/apps/APISuite/
              ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP_STG "cd /apps/APISuite/ && ./merge_env.sh && docker-compose pull && docker-compose up -d && docker image prune --force"

  # deploy-carnext:
  #     executor: apisuite-executor
  #     steps:
  #       - checkout
  #       - attach_workspace:
  #           at: ./util
  #       - run:
  #           name: Fix ssh could not resolve hostname
  #           command: |
  #             ssh-keyscan $DROPLET_IP_CN >> ~/.ssh/known_hosts
  #       - add_ssh_keys:
  #           fingerprints:
  #             - "92:92:37:9c:7c:b4:e2:93:0a:f7:ac:f7:c6:74:b8:61"
  #       - run:
  #           name: Deploy Over SSH
  #           command: |
  #             chmod +x ./util/clean_compose.sh
  #             (cd ./util && ./clean_compose.sh)
  #             chmod +x ./util/merge_env.sh
  #             scp -o StrictHostKeyChecking=no ./util/.env ./util/environment ./util/docker-compose.yml ./util/merge_env.sh $DROPLET_USER@$DROPLET_IP_CN:/apps/APISuite/
  #             ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP_CN "cd /apps/APISuite/ && ./merge_env.sh && docker-compose pull && docker-compose up -d && docker image prune --force"

workflows:
  version: 2
  build:
    jobs:
        - test
        - build:
            filters:
                branches:
                  only:
                    - develop
                    - staging
                    - feat/APIS-438
            requires:
                - test
        - deploy-dev:
            filters:
                branches:
                  only:
                    - develop
            requires:
                - build
        - deploy-stg:
            filters:
                branches:
                  only:
                    - staging
            requires:
                - build
        # - deploy-carnext:
        #     filters:
        #         branches:
        #           only:
        #             - develop
        #     requires:
        #         - build
