version: 2
jobs:
  test:
      working_directory: ~/apisuite
      docker:
        - image: circleci/node:12.13.1
      steps:
        - checkout
        - run:
            name: Build packages with docker-compose and push to registry
            command: |
              sudo apt-get install jq
              cd util
              chmod +x common.sh
              chmod +x run_tests.sh
              ./run_tests.sh

  build:
      working_directory: ~/apisuite
      docker:
        - image: circleci/buildpack-deps:stretch
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build packages with docker-compose and push to registry
            command: |
              sudo apt-get install ruby-full jq
              cd util
              chmod +x build_push_docker.sh
              ./build_push_docker.sh

  deploy:
      working_directory: ~/apisuite
      docker:
        - image: circleci/node:12.13.1
      steps:
        - run:
            name: Fix ssh could not resolve hostname
            command: |
              ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
        - add_ssh_keys:
            fingerprints:
              - "92:92:37:9c:7c:b4:e2:93:0a:f7:ac:f7:c6:74:b8:61"
        - run:
            name: Deploy Over SSH
            command: |
              ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "cd /apps/APISuite/util && docker-compose pull && docker-compose up -d && docker image prune --force"

workflows:
  version: 2
  build:
    jobs:
        - test
        - build:
            filters:
                branches:
                  only:
                    - develop
            requires:
                - test
        # - deploy:
        #     filters:
        #         branches:
        #           only:
        #             - develop
        #     requires:
        #         - build
