version: 2.1

executors:
  node12-executor:
    docker:
      - image: circleci/node:12.20.1

jobs:
  test:
    executor: node12-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./run_tests.sh

  release:
    executor: node12-executor
    steps:
      - checkout
      - run: npm install
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  build:
    executor: node12-executor
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: mkdir ~/.ssh/
      - run: echo "${echo $GITHUB_SSH_PRIVATE_KEY_BASE64 | base64 -d}" > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: touch ~/.ssh/known_hosts
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: ./build.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - add_ssh_keys:
          fingerprints:
            - 31:96:89:eb:aa:ee:09:68:3a:6b:10:ad:d0:95:81:80
      - attach_workspace:
          at: ~/
      - run: ./deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          context: docker
          filters:
            branches:
              only:
                - develop
                - staging
                - production
          requires:
            - test
      - build:
          context: docker
          filters:
            branches:
              only:
                - develop
                - staging
                - production
          requires:
            - release
      - deploy:
          context: vmachines
          filters:
            branches:
              only:
                - develop
                - staging
                - production
          requires:
            - build
