version: 2.1

executors:
  node12-executor:
    docker:
      - image: circleci/node:12.20.1

jobs:
  test:
    executor: node12-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run pretest
# No relevant tests for now. Leaving pretest for linter & type check
#      - run:
#          name: Run tests
#          command: |
#            ./install_dependencies.sh
#            ./run_tests.sh

  release:
    executor: node12-executor
    steps:
      - checkout
      - run: GH_TOKEN=$GH_TOKEN npx semantic-release
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - run: ./build.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: ~/
      - run: ./deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          context: docker
          filters:
            branches:
              only:
                - develop
                - staging
                - production
          requires:
            - test
#      - build:
#          context: docker
#          filters:
#            branches:
#              only:
#                - develop
#                - staging
#                - production
#          requires:
#            - release
#      - deploy:
#          context: vmachines
#          filters:
#            branches:
#              only:
#                - develop
#                - staging
#                - production
#          requires:
#            - build
