version: 2.1
executors:
  publisher:
    environment:
      IMAGE_NAME: erettozi/apisuite-client-sandbox:dev
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
 test:
    working_directory: ~/project/packages/apisuite-client-sandbox
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: 
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build Project
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/apisuite-client-sandbox

 build:
    executor: publisher
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: packages/apisuite-client-sandbox
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: packages/apisuite-client-sandbox
          paths:
            - ./image.tar

workflows:
 version: 2
 build_deploy:
   jobs:
     - test
     - build:
        filters:
          branches:
            only:
              - test-deploy
        requires:
          - test