version: 2
jobs:
  build_apisuite:
      working_directory: ~/apisuite
      machine:
        image: "true"
      steps:
        - checkout
        - run:
            name: Build packages with docker-compose and push to registry
            command: |
              cd docker
              chmod +x build_push_docker.sh
              ./build_push_docker.sh
  deploy_apisuite:
      working_directory: ~/apisuite
      machine:
        image: "true"
      steps:
        - checkout
        - run:
            name: deploy packages with docker-compose
            command: ssh -o StrictHostKeyChecking=no root@206.189.118.141 "cd /apps/APISuite/docker && docker-compose pull && docker-compose up -d && docker image prune --force"
workflows:
  version: 2
  build:
    jobs:
        - build_apisuite
        - deploy_apisuite
