version: '3.2'
services:
  sandbox-client-dev:
    build: '../packages/apisuite-client-sandbox'
    image: ${DOCKER_REPO}:${APISUITE_CLIENT_SANDBOX_TAG}
    container_name: apisuite-client-sandbox-${APISUITE_ENVIRONMENT}
    restart: on-failure
    ports:
      - ${APISUITE_SANDBOX_PORTS}
    networks:
      - apisuite-network

networks:
  apisuite-network:
    external:
      name: apisuite-network
