import { makeStyles } from '@material-ui/core/styles'

export default makeStyles((theme) => ({
  root: {
    minHeight: '100%',
    backgroundColor: theme.palette.grey[100],
  },
  contentContainer: {
    maxWidth: 900,
    margin: '0 auto',
    transform: 'translateX(-8px)',
  },
  title: {
    fontSize: 26,
    fontWeight: 300,
    marginBottom: 54,
  },
  table: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    cursor: 'pointer',
    borderRadius: theme.palette.dimensions.borderRadius,
    backgroundColor: 'white',
    overflow: 'hidden',
    borderStyle: 'solid',
    borderColor: theme.palette.grey[300],
    border: 1,
  },
  header: {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 42,
    paddingLeft: 10,
    color: theme.palette.grey[400],
  },
  actions: {
    paddingRight: 178,
  },
  row: {
    display: 'flex',
    padding: '16px 30px 16px 10px',
    justifyContent: 'space-between',
    width: '100%',
    borderTop: `1px solid ${theme.palette.grey[300]}`,
  },
  auth: {
    fontSize: 14,
    color: theme.palette.text.secondary,
  },
  select: {
    width: 182,
  },
  name: {
    fontSize: 16,
    color: theme.palette.text.primary,
  },
  btn: {
    display: 'inline-block',
    color: 'white',
    padding: '8px 24px',
    backgroundColor: theme.palette.grey[900],
    borderRadius: theme.palette.dimensions.borderRadius,
    cursor: 'pointer',
    fontWeight: 500,
    marginRight: 16,
    '&:disabled': {
      backgroundColor: theme.palette.grey[400],
    },
  },
  inviteCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    cursor: 'pointer',
    borderRadius: theme.palette.dimensions.borderRadius,
    backgroundColor: 'white',
    overflow: 'hidden',
    borderStyle: 'solid',
    borderColor: theme.palette.grey[300],
    border: 1,
    marginTop: 24,
    height: 82,
    padding: '12px 30px 12px 10px',
  },
  emailTextfield: {
    backgroundColor: 'white',
    width: 220,
    borderRadius: theme.palette.dimensions.borderRadius,
    color: theme.palette.grey[400],
  },
  nameTextfield: {
    backgroundColor: 'white',
    width: 220,
    borderRadius: theme.palette.dimensions.borderRadius,
    color: theme.palette.grey[400],
  },
  loading: {
    position: 'relative',
    top: 4,
    color: 'white',
    opacity: 0.5,
  },
  loadingPage: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorPlaceholder: {
    display: 'flex',
    marginTop: 10,
  },
  errorAlert: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: theme.palette.error.main,
    border: 'solid',
    borderWidth: 1,
    borderColor: theme.palette.error.main,
    fontSize: 13,
    color: '#FFF',
    padding: '2px 15px',
    borderRadius: theme.palette.dimensions.borderRadius,
    minHeight: 20,
  },
}))
