version: "3.5"
services:
  kong-database-postgres:
    image: postgres:9.5
    container_name: kong-database-postgres
    restart: always
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    ports:
      - 5432:5432
    networks:
      - kong-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong-database-migrations:
    image: kong-database-migrations
    container_name: kong-database-migrations
    build: .
    restart: on-failure
    command: "kong migrations up --v"
    volumes:
      - ./config:/etc/kong
      - ./plugins:/plugins
      - ./rocks:/rocks
    environment:
      #- KONG_LICENSE_DATA='{"license":{"signature":"fba8d94d273f29e39ebf5f8e93f46b5e9e5265708d74bf2afc912ecc0bab55f8baaa1f583db1a8cf4d86abe09051dcae98092b0d153fdaf0830bd82b8cdfa211","payload":{"customer":"cloudoki","license_creation_date":"2018-09-21","product_subscription":"Kong Enterprise Edition","admin_seats":"5","support_plan":"None","license_expiration_date":"2018-10-21","license_key":"00Q4100000wKqnuEAC_a1V41000006MqrsEAC"},"version":1}}'
      - KONG_PG_HOST=kong-database-postgres
      #- KONG_CUSTOM_PLUGINS="docker-manager"
    networks:
      - kong-network
    depends_on:
      - kong-database-postgres

  kong-api-gateway:
    image: kong-api-gateway
    build: .
    restart: always
    container_name: kong-api-gateway
    command: >
      sh -c "kong migrations up && sh /docker-entrypoint.sh kong docker-start"
    volumes:
      - ./config:/etc/kong
      - ./plugins:/plugins
      - ./rocks:/rocks
    environment:
      #- KONG_LICENSE_DATA='{"license":{"signature":"fba8d94d273f29e39ebf5f8e93f46b5e9e5265708d74bf2afc912ecc0bab55f8baaa1f583db1a8cf4d86abe09051dcae98092b0d153fdaf0830bd82b8cdfa211","payload":{"customer":"cloudoki","license_creation_date":"2018-09-21","product_subscription":"Kong Enterprise Edition","admin_seats":"5","support_plan":"None","license_expiration_date":"2018-10-21","license_key":"00Q4100000wKqnuEAC_a1V41000006MqrsEAC"},"version":1}}'
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database-postgres
      #- KONG_PROXY_LISTEN="0.0.0.0:8000, 0.0.0.0:8443 ssl"
      #- KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      #- KONG_CUSTOM_PLUGINS="docker-manager, scenario-manager, api-manager"
    depends_on:
      - kong-database-postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong-api-gateway:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    networks:
      - kong-network
    ports:
      - 8001:8001
      - 8443:8443
      - 8445:8445
      - 8000:8000
      - 8002:8002
      - 8003:8003

networks:
  kong-network:
    name: kong-global-network
